//create a function that will send and alert.
function imageEvent(){
    alert("hi");
}

//Created a function that will play a noise when the button is clicked.
function noise(){
    var X = document.getElementById("Music");
    X.play();
}

//Create a function that will turn the text color red when the event is driven.
function submitEvent(){
    document.getElementById("fname").style.color = "red";
}